spring.application.name=registeration

server.port=9191

spring.datasource.url=jdbc:postgresql://postgres:5432/registeration_db
spring.datasource.username=postgres
spring.datasource.password= Arti2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=admin123

jwt.secret=your-very-long-secret-key-string-here-change-it
